# Generated by Django 5.1 on 2024-08-13 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('visits', models.IntegerField(default=0)),
                ('data_sent', models.BigIntegerField(default=0)),
                ('data_received', models.BigIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='sites.site')),
            ],
            options={
                'unique_together': {('site', 'path')},
            },
        ),
    ]
