# Generated by Django 5.1 on 2024-08-20 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_site_options_alter_site_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitestatistics',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='response_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='status_code',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='unique_visitors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
