# Generated by Django 5.1 on 2024-08-20 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_sitestatistics_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitestatistics',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='last_visit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
