# Generated by Django 5.1 on 2024-08-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_remove_sitestatistics_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitestatistics',
            name='unique_visitors',
        ),
    ]
