# Generated by Django 5.1 on 2024-08-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_remove_sitestatistics_unique_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitestatistics',
            name='css_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='css_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='html_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='html_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='image_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='image_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='js_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='js_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='other_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='other_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
